# Generated by Django 3.2.13 on 2022-11-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('전체', '전체'), ('커리어', '커리어'), ('이직', '이직'), ('회사생활', '회사생활'), ('일상', '일상'), ('개발', '개발'), ('마케팅', '마케팅'), ('질문', '질문'), ('HR', 'HR'), ('기타', '기타')], max_length=50),
        ),
    ]
