# Generated by Django 3.2.13 on 2022-11-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='count',
            new_name='search_count',
        ),
    ]
