# Generated by Django 3.2.13 on 2022-11-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('pseudo_position', models.CharField(max_length=100)),
                ('company_job', models.TextField()),
            ],
        ),
    ]
