# Generated by Django 3.2.13 on 2022-11-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_githuburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.DateField(),
        ),
    ]
