# Generated by Django 3.2.13 on 2022-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.IntegerField(default=0),
        ),
    ]
