# Generated by Django 3.2.13 on 2022-11-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_career'),
        ('accounts', '0003_note'),
    ]

    operations = [
    ]
