# Generated by Django 3.2.13 on 2022-11-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_career'),
        ('accounts', '0004_alter_user_login_method'),
    ]

    operations = [
    ]
