# Generated by Django 3.2.13 on 2022-11-15 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0003_alter_user_career_0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
