# Generated by Django 3.2.13 on 2022-11-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0003_user_career_0004_alter_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('Google', 'Google')], default='email', max_length=6),
        ),
    ]
