# Generated by Django 3.2.13 on 2022-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
