# Generated by Django 3.2.13 on 2022-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='githuburl',
            field=models.URLField(default=''),
        ),
    ]
