# Generated by Django 3.2.13 on 2022-11-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='read_check',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
