# Generated by Django 3.2.13 on 2022-11-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_githuburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='githuburl',
            field=models.URLField(null=True),
        ),
    ]
