# Generated by Django 3.2.13 on 2022-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_githuburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='githuburl',
            field=models.URLField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
